### ISSUE TITLE
Enable advanced-instances tier?

### ISSUE THREAD

**Issue by jtlz2** [aws-samples/sagemaker-ssh-helper#11]
Hi - I have high hopes for the sagemaker-ssh-helper, for which thanks!

After setup, upon running

```bash
ssh -i ~/.ssh/sagemaker-ssh-gw -p 10022 root@localhost
```

at the end I get:

```
An error occurred (BadRequest) when calling the StartSession operation: Enable advanced-instances tier to use Session Manager with your on-premises instances
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

The error aside, does this mean the library will only work with the "advanced-instances tier"?? How does one know if one has this? I am trying to SSH into a plain old sagemaker instance... Help!

**Comment by ivan-khvostishkov** [comment]
Hi, jtlz2! Thank you for your interest in SageMaker SSH Helper!

The error that you've shared is probably happening when you run one of the `sm-local-ssh-*` commands, before you ssh to localhost.

Indeed, it means that you need to enable the [Advanced Instances Tier](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managed-instances-tiers.html). This step is described in [IAM_SSM_Setup.md](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/IAM_SSM_Setup.md) in section 2h:

> Enable advanced instances tier to use managed instances (such as SageMaker managed containers): Systems Manager > Fleet Manager > Account management > Instance tier settings > Change account setting > Confirm change from Standard-Tier to Advanced-Tier

As described in the Systems Manager doc, you need to enable it, because you're connecting to the hybrid-activated nodes. In case of SageMaker SSH Helper, these nodes are SageMaker containers.

Let me know if this answers your question.

Please, also note in #4 that "plain old" SageMaker Notebook instances are not fully supported by SageMaker SSH Helper at this moment.
