### ISSUE TITLE
Is there any additional cost&limits related to using (SSM) Session Manager?

### ISSUE THREAD

**Issue by cceyda** [aws-samples/sagemaker-ssh-helper#24]
This link leads me to believe no https://aws.amazon.com/systems-manager/pricing/#Session_Manager. but SSM's pricing is a bit confusing to me and I don't wanna be surprised.
And does this feature still need requesting to be allowlisted: https://docs.aws.amazon.com/sagemaker/latest/dg/ssm-access.html#Allowlist
I don't see anything in the readme.

**Comment by ivan-khvostishkov** [comment]
Hi, @cceyda, thank you for your interest. For me, the link from the documentation leads to https://aws.amazon.com/systems-manager/pricing/#On-Premises_Instance_Management , i.e., to the section "On-Premises Instance Management" . It shows the price "per advanced on-premises instance per hour". SageMaker SSH Helper uses the activation mechanism for on-premises instances to connect SageMaker containers to Systems Manager, so this is the pricing section that will be the most relevant for you.

If your AWS account doesn't have any on-premises instances connected with Standard Tier, you shouldn't have any surprises, the fee is very minimal. To clear any further concerns about AWS pricing and billing, I recommend to reach out to [AWS Support](https://aws.amazon.com/contact-us/).

As for the second link, you might have noticed that this is relevant only for SageMaker Inference. This is a relatively new native feature, implemented by SageMaker team. SageMaker SSH Helper doesn't use this feature and you don't need to be allowlisted, therefore it's not mentioned in the README. But I will add it to the FAQ.

Hope it helps!

**Comment by cceyda** [comment]
No additional questions. But it would be better if we didn't have to switch a fundamental setting related to the account that would have to be managed carefully or would occur fees if we are not careful even for instances that are not going to be using the sagemaker-ssh-helper. Especially for enterprise settings we are not even always allowed to change.

Too much work just for such a basic necessity/feature like SSH. I'll stick to using other workarounds like rolling out my own solution with ngrok.

**Comment by ivan-khvostishkov** [comment]
Hi, @cceyda . I understand your concerns. Please, keep in mind that SageMaker SSH Helper is not a native feature of Amazon SageMaker. There's a similar native feature that allows [SSM container access for SageMaker endpoints](https://docs.aws.amazon.com/sagemaker/latest/dg/ssm-access.html), but take a note of this important information in the documentation:
> You have to contact customer support, and get your account allowlisted, to use this feature.

So, it also have to be managed carefully, and applies to the whole AWS account.

If you have other non-ML workloads in your AWS account that you think can be affected from any of per-account settings, and it applies not only to the SSH/SSM feature, I recommend to separate these workloads into multiple accounts, as explained in the documentation:

[Do I need multiple AWS accounts?](https://docs.aws.amazon.com/accounts/latest/reference/welcome-multiple-accounts.html)

> An account is the only true way to separate items at a billing level. Multiple accounts help separate items at a billing level across business units, functional teams, or individual users. 

Note that when you use Amazon SageMaker, you're already using other AWS services that incur additional charges, for example, Amazon S3. Therefore, I don't think you should go to an extreme solution, and create your own solution from scratch just because you need to use another AWS service in addition to SageMaker. 

Of course, you're free to implement the solution with ngrok, but also keep in mind that the total cost of ownership consists not only of the costs of infrastructure, but also of operational costs, and of the security & compliance costs.

Hope it gives you some useful insights.
