### ISSUE TITLE
[Feature] SageMaker Notebook Instances support

### ISSUE THREAD

**Issue by austinmw** [aws-samples/sagemaker-ssh-helper#4]
Hi, will this package work to connect VS Code to a standard SM notebook? I'm currently using an EC2 bastion to ssh through, so would be really nice if this simplified the process.

**Comment by gilinachum** [comment]
Did you mean SageMaker Notebook Instance? it's currently not supported.
Instructions for SageMaker Studio Notebooks is [here](https://github.com/aws-samples/sagemaker-ssh-helper#studio).

**Comment by austinmw** [comment]
@gilinachum Hi, yes, SageMaker Notebook Instance. Thanks for your suggestion; I tried that code-server solution, but found that the lack of extensions was too big of a con for me personally. Unfortunately I also can't use Studio Notebooks because they're not available in all regions and don't support Local Mode. 

Is there already an existing feature request for SageMaker Notebook Instance support?

**Comment by ivan-khvostishkov** [comment]
Hi, Austin,

Let's keep this issue open as a feature request. 

In a meantime I suggest taking an alternative approach, as described in the section [Remote code execution with PyCharm / VSCode over SSH](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/README.md#remote-interpreter). 

You submit a long-running placeholder training job from VS Code on your local machine, then connect to this job with VS Code over SSH and run your code remotely again and again as much times as you need. 

As a result, you get a real training container with all environment variables set by SageMaker, so there's less need in local mode in this case. Moreover, if you need GPU, you can select any instance type you need instead of keeping a single large GPU notebook instance running all the time. This is how you can easily switch instances and reduce costs. Even more, you can choose to start a cluster of multiple instances for iterating faster on distributed training jobs.

Regards,
Ivan

**Comment by ivan-khvostishkov** [comment]
Notebook instances support now [has been added](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/FAQ.md#are-sagemaker-notebook-instances-supported).
