### ISSUE TITLE
[Question] Shell environment different from web terminal 

### ISSUE THREAD

**Issue by djmarti** [aws-samples/sagemaker-ssh-helper#48]
Hi,

I manage to connect to my notebook instance with `sm-local-ssh-notebook connect <my_notebook>`, as described in the instructions. I log in as root, inside what seems to be a docker container (checked with [this command](https://stackoverflow.com/a/37015387/3479163)), with no users under `/home`. In contrast, when launching a web-based terminal from the notebook, the environment is very different: the default user is `ec2-user`, user files are under `/home/ec2-user`, and it seems I am not in a docker container. 

What extra steps are needed to have the same type of environment as in the web-terminal, but using `sagemaker-ssh-helper`? Basically, all I want is to be able to do exactly the same I can do in the web-based Terminal from my sagemaker-ssh-helper session.

Maybe this has been addressed somewhere, but I didn't find any reference.

Thanks for your help.

**Comment by ivan-khvostishkov** [comment]
Hi, @djmarti , thanks for your interest in using SageMaker SSH Helper for notebook instances.

The fact that you're seeing two slightly different directory trees is the expected behavior and the limitation of the SSH Helper support for SageMaker notebook instances.

You can find more details and the explanation in this conversation:
https://github.com/aws-samples/sagemaker-ssh-helper/issues/40#issuecomment-1790958016

If you want identical environments, I recommend switching to SageMaker Studio Classic. There will still be caveats like checking the presence of the conda env and activating the right env if needed, but this is still the better experience.

Let me know if you have more questions.

**Comment by djmarti** [comment]
Thanks Ivan for the answer and the pointer. Not a big deal in the end, I was just curious.
